name: Update Site

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_ROLE: ${{ secrets.AWS_ROLE }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Pandoc
      run: sudo apt update && sudo apt install -y pandoc

    - name: Process README #and Upload to S3
      run: >
        pandoc --standalone --template ${{github.workspace}}/site_files/template.html
        ${{github.workspace}}/README.md --metadata title="pandoc_complains_without_title"
      #| aws s3 cp - s3://$BUCKET_NAME/index.html
